# Generated by Django 3.2.8 on 2021-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/images')),
                ('title', models.CharField(max_length=100)),
                ('blog_texts', models.TextField(max_length=3000)),
                ('category', models.CharField(choices=[('T', 'Travel'), ('SP', 'Sports'), ('N', 'Nature')], max_length=2)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
