# Generated by Django 3.2.8 on 2021-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Sport', 'Sport'), ('Nature', 'Nature')], max_length=10),
        ),
    ]
